In [1]:
import pandas as pd
import numpy as np

In [2]:
%%time
# Считать собранный датасет
data = pd.read_csv('..\..\T21\df_consolidated.csv')
data['date'] = pd.to_datetime(data['date'], format='%Y%m%d %H:%M:%S')
data = data.set_index(['date'])
data.sort_index()
print(data.shape)
print('Tickers ',len(data.ticker.unique()))

(12324790, 197)
Tickers  147
Wall time: 6min 31s

In [3]:
data.head()

,close,high,low,open,volume,action_buy,action_sell,ticker,dayofweek,hour,...,minus_di96,adx96,plus_di480,minus_di480,adx480,cci_24,cci_100,cci_240,cci_480,cci_960
date,,,,,,,,,,,,,,,,,,,,,
2019-01-08 14:50:00+00:00,37.4075,37.4450,37.3400,37.3825,676652,0,0,AAPL,1,14,...,34.404902,9.188783,25.151021,31.629050,15.840743,123.573269,192.813372,156.894160,89.166879,-1.410136
2019-01-08 14:55:00+00:00,37.2525,37.4500,37.2250,37.4075,787708,0,0,AAPL,1,14,...,35.125959,9.136240,24.989168,31.736553,15.826827,60.234424,131.453249,120.820693,76.437796,-5.839856
2019-01-08 15:00:00+00:00,37.3200,37.3325,37.2375,37.2550,714752,0,0,AAPL,1,15,...,34.112351,9.048905,24.878313,31.595765,15.814491,47.774651,120.471950,114.967170,74.518156,-6.372992
2019-01-08 15:05:00+00:00,37.3650,37.3825,37.3175,37.3200,399092,0,0,AAPL,1,15,...,33.342808,8.962641,24.943145,31.497034,15.802204,78.896438,153.122129,136.338504,82.793815,-3.261457
2019-01-08 15:10:00+00:00,37.2900,37.4300,37.2575,37.3650,524456,0,0,AAPL,1,15,...,33.056404,8.892565,24.924281,31.473269,15.789085,55.253132,131.601806,123.782464,78.463033,-4.653306

In [4]:
df = data.sample(1000000).sort_index()  #(12324790, 197)
df = df[['ticker','close']]
df = df.reset_index()
df = df.pivot(index='date', columns='ticker', values='close')
df = df.fillna(method = 'ffill')
df = df.fillna(method = 'bfill') ## temporary approach
print(df.shape)
print(df.isnull().sum())
print(df.isnull().sum().sum())
print( 'Inf -> ', df.columns.to_series()[np.isinf(df).any()] ) # Check Inf
df = df.reset_index()

(152212, 147)
ticker
A       0
AAPL    0
ADBE    0
ADP     0
AFG     0
       ..
WRB     0
WSM     0
XEL     0
YELP    0
YNDX    0
Length: 147, dtype: int64
0
Inf ->  Series([], Name: ticker, dtype: object)

In [5]:
compression_opts = dict(method='zip', archive_name='..\SampleData\stock_5min_v20220613.csv')  
df.to_csv('..\SampleData\stock_5min_v20220613.zip', compression=compression_opts)